file:
  input-dir: input
  output-dir: output
  input-file-name: employee.csv
  output-file-name: employee.tbl
  page-size: 4096
  no-of-pages: 10
  record-size: 112
  offset-size: 2
  page-header-size: 2